-- ============================================================================
-- TESTING WORKFLOW / خطوات الاختبار
-- ============================================================================

-- ============================================================================
-- STEP 1: Execute Schema First
-- ============================================================================
-- 1. Go to Supabase Dashboard > SQL Editor
-- 2. Copy contents of supabase_schema.sql
-- 3. Run the SQL

-- ============================================================================
-- STEP 2: Create Auth Users (Required before seed data)
-- ============================================================================
-- You MUST create users in Supabase Auth first:
-- 1. Supabase Dashboard > Authentication > Users
-- 2. Click "Add user" or "Invite user"
-- 3. Create these users:

-- Email: admin@alyoussef.edu | Password: any password | Role: admin
-- Email: teacher1@alyoussef.edu | Password: any password | Role: teacher  
-- Email: teacher2@alyoussef.edu | Password: any password | Role: teacher
-- Email: parent1@alyoussef.edu | Password: any password | Role: parent
-- Email: parent2@alyoussef.edu | Password: any password | Role: parent
-- Email: parent3@alyoussef.edu | Password: any password | Role: parent

-- Note: The UUIDs will be generated by Supabase. Update the seed_data.sql 
-- with the actual UUIDs from your Supabase auth users.

-- ============================================================================
-- STEP 3: Execute Seed Data
-- ============================================================================
-- 1. Get the UUIDs from Supabase Auth (Users table)
-- 2. Update seed_data.sql with actual UUIDs
-- 3. Run seed_data.sql in SQL Editor

-- ============================================================================
-- STEP 4: Test via Frontend
-- ============================================================================
-- 1. Start Next.js: npm run dev
-- 2. Open http://localhost:3000
-- 3. Login with admin@alyoussef.edu
-- 4. Test the admin dashboard

-- ============================================================================
-- STEP 5: Test via API (using curl or Postman)
-- ============================================================================

-- Quick API Test Commands:

-- 1. LOGIN
-- curl -X POST http://localhost:3000/api/auth/login \
--   -H "Content-Type: application/json" \
--   -d '{"email": "admin@alyoussef.edu", "password": "your_password"}'

-- 2. GET STUDENTS (requires Bearer token from login response)
-- curl -X GET http://localhost:3000/api/students \
--   -H "Authorization: Bearer YOUR_JWT_TOKEN"

-- 3. CREATE STUDENT
-- curl -X POST http://localhost:3000/api/students \
--   -H "Content-Type: application/json" \
--   -H "Authorization: Bearer YOUR_JWT_TOKEN" \
--   -d '{
--     "name": "Test Student",
--     "student_code": "STU999",
--     "class_id": "CLASS_UUID_HERE",
--     "parent_id": "PARENT_UUID_HERE"
--   }'

-- 4. CREATE CLASS
-- curl -X POST http://localhost:3000/api/classes \
--   -H "Content-Type: application/json" \
--   -H "Authorization: Bearer YOUR_JWT_TOKEN" \
--   -d '{
--     "name": "الصف الرابع - أ",
--     "grade_level": 4,
--     "section": "أ",
--     "academic_year": "2024-2025",
--     "capacity": 30
--   }'

-- 5. CREATE TEACHER
-- curl -X POST http://localhost:3000/api/teachers \
--   -H "Content-Type: application/json" \
--   -H "Authorization: Bearer YOUR_JWT_TOKEN" \
--   -d '{
--     "name": "New Teacher",
--     "specialization": "العلوم",
--     "phone": "0500000000"
--   }'

-- ============================================================================
-- VERIFICATION QUERIES / استعلامات للتحقق
-- ============================================================================

-- Check all tables have data
SELECT 'users' as table_name, COUNT(*) as count FROM users
UNION ALL SELECT 'parents', COUNT(*) FROM parents
UNION ALL SELECT 'students', COUNT(*) FROM students
UNION ALL SELECT 'teachers', COUNT(*) FROM teachers
UNION ALL SELECT 'classes', COUNT(*) FROM classes
UNION ALL SELECT 'subjects', COUNT(*) FROM subjects
UNION ALL SELECT 'announcements', COUNT(*) FROM announcements
UNION ALL SELECT 'attendance', COUNT(*) FROM attendance
UNION ALL SELECT 'grades', COUNT(*) FROM grades
UNION ALL SELECT 'payments', COUNT(*) FROM payments;

-- Check students with their classes and parents
SELECT 
    s.name as student_name,
    s.student_code,
    c.name as class_name,
    p.name as parent_name,
    u.email as parent_email
FROM students s
JOIN classes c ON s.class_id = c.id
JOIN parents p ON s.parent_id = p.id
JOIN users u ON p.user_id = u.id;

-- Check pending payments
SELECT 
    s.name as student_name,
    p.type,
    p.amount,
    p.paid_amount,
    p.remaining_amount,
    p.is_paid
FROM payments p
JOIN students s ON p.student_id = s.id
WHERE p.is_paid = false;

-- ============================================================================
-- END TESTING GUIDE
-- ============================================================================
